In [6]:
import numpy as np
import random as ran
#generar un arreglo
F_u = []

for i in range(5):
    F_u.append(i*2)
print(F_u)
F_u1 = np.asarray(F_u)
F_u = np.transpose(F_u1)
print(F_u)

[0, 2, 4, 6, 8]
[0 2 4 6 8]


In [7]:
jb = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        jb[i][j] = ran.randint(2,9)

print(jb)

det = np.linalg.det(jb)
print(det)

jb2 = jb.transpose()
print('-----\nTraspuesta: \n',jb2)

jb3 = np.linalg.inv(jb)
print('-----\nInversa: \n',jb3)

[[5. 9. 2. 4. 4.]
 [8. 9. 5. 3. 2.]
 [8. 2. 5. 4. 3.]
 [5. 9. 7. 2. 7.]
 [7. 4. 4. 6. 6.]]
-554.0000000000001
-----
Traspuesta: 
 [[5. 8. 8. 5. 7.]
 [9. 9. 2. 9. 4.]
 [2. 5. 5. 7. 4.]
 [4. 3. 4. 2. 6.]
 [4. 2. 3. 7. 6.]]
-----
Inversa: 
 [[ 1.40794224 -1.22021661  1.72563177  0.10108303 -1.51263538]
 [-0.07942238  0.20216606 -0.25631769 -0.01083032  0.12635379]
 [-1.55054152  1.31046931 -1.57220217 -0.05234657  1.44404332]
 [-1.68411552  1.55956679 -2.04873646 -0.29783394  1.97472924]
 [ 1.12815884 -1.14440433  1.25451264  0.22202166 -1.09025271]]


In [36]:
jb2 = jb.transpose()
print(jb2)
L = [1,2,3,4,5]

A = np.dot(jb2,L)
print(A)

[[5. 8. 8. 5. 7.]
 [9. 9. 2. 9. 4.]
 [2. 5. 5. 7. 4.]
 [4. 3. 4. 2. 6.]
 [4. 2. 3. 7. 6.]]
[100.  89.  75.  60.  75.]


In [47]:
A = np.matrix([[3,4],[5,6]])
print(A)
b = [1,2]

X = np.dot(A,b)
print(X)
J = [1,2] + X
print(J)

[[3 4]
 [5 6]]
[[11 17]]
[[12 19]]


In [1]:
arreglo = [3,4,55,77,34,11,32]

for i,valor in enumerate(arreglo):
    print(valor,'SI')

3 SI
4 SI
55 SI
77 SI
34 SI
11 SI
32 SI


In [2]:
link_cells = [[2,4],[3,5],[8,22],[22,33]]
a = link_cells[2]
print(a)

[8, 22]


In [4]:
totCells = 4
for i in range(totCells):
    print(link_cells[i])

[2, 4]
[3, 5]
[8, 22]
[22, 33]


In [34]:
import numpy as np
A = np.ones(5)
M = np.diag(np.ones(3))
B = [[2,3,4],[1,2,1],[1,0,2]]
print(M*2)

L = [2,3,4,5]
M = np.asfarray(L) * 3
largo = np.ndarray(L)
print('what',largo)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
what [[[[5.82538573e-212             nan 1.12646967e-321 8.96904655e-067
    5.20269528e-090]
   [6.01347002e-154 6.01347002e-154 6.37257830e-067 5.20748563e-090
    7.10600526e-038]
   [1.21268108e-099 6.01346953e-154 8.60827300e-067 7.72601340e+140
    1.30408776e-076]
   [3.92574737e+179 5.60302087e-067 3.75924450e+179 5.60374534e-067
    3.11213421e+179]]

  [[1.30489232e-076 3.43443295e+179 6.01334530e-154 1.13053120e-042
    7.86058637e-067]
   [3.89202787e-086 1.48441290e-076 3.64465893e-086 3.37612237e-057
    3.44358551e-086]
   [6.38274374e-067 4.04681495e-086 1.17820816e-047 5.98151975e-154
    1.42715292e-071]
   [1.79339645e-052 6.14099335e-071 3.93800552e-062 1.56000472e-033
    2.31900848e-052]]

  [[5.53825660e-048 1.17660554e-047 1.96852985e-062 2.31860379e-052
    2.44297929e-154]
   [5.93622403e-038 5.08076004e-067 5.98129863e-154 3.21804318e-057
    1.79258078e-052]
   [5.88839140e-062 4.75408875e-038 4.75961306e-038 1.10689752e-